project:
  type: website

website:
  title: "summer-quarto"
  navbar:
    left:
      - href: index.qmd
        text: Course Materials
      - slides/00-Hello/00-Hello.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



