project:
  type: website
  output-dir: docs

website:
  title: "Summer Quarto"
  site-url: https://ottaviae.github.io/summer-quarto/
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Slides"
        href: slide.qmd

format:
  html:
    css: styles.css
    toc: true



